print("Bienvenidos a python 2")
print("#####Cartel 6 B#####")
print("######PROGRAMANDO######")
print("######ESTUDIANDO#######")
print("######APRENDIENDO######")
print("#SE CREARAN PROYECTOS#$")
print("💀😍😘💕👌🌟😊😂😺🐈")
print(".                        ")
print(".  ##LA FRASE DEL DIA ES##")
print("EL CONOCIMIENTO ES PODER🤩")
print("entonces apliquemonos👍")
print("BIENVENIDOS AL CICLO 2025-2026")